name: Release Please

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: release-please

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release

  release-pypi:
    name: Release to PyPI
    uses: ./.github/workflows/pypi-release.yml

    needs: release-please
    if: needs.release-please.outputs.releases_created == 'true'

    secrets: inherit
